// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr3PTUzHBFXhDpQ8S2wN7XXW_-QIHowTg',
    appId: '1:252443331104:web:12dbd56448ca8ae435ca45',
    messagingSenderId: '252443331104',
    projectId: 'skill-exchange-457f3',
    authDomain: 'skill-exchange-457f3.firebaseapp.com',
    storageBucket: 'skill-exchange-457f3.firebasestorage.app',
    measurementId: 'G-MXSJSH3FCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDE7-YKN-1RhwShp-XUToH_gcU2P5h2lb0',
    appId: '1:252443331104:android:2b7e0597044f337535ca45',
    messagingSenderId: '252443331104',
    projectId: 'skill-exchange-457f3',
    storageBucket: 'skill-exchange-457f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYofOYQGfN6EpUO_TCD6P3Rh9nYYuA28o',
    appId: '1:252443331104:ios:db33b8b185394c1935ca45',
    messagingSenderId: '252443331104',
    projectId: 'skill-exchange-457f3',
    storageBucket: 'skill-exchange-457f3.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYofOYQGfN6EpUO_TCD6P3Rh9nYYuA28o',
    appId: '1:252443331104:ios:db33b8b185394c1935ca45',
    messagingSenderId: '252443331104',
    projectId: 'skill-exchange-457f3',
    storageBucket: 'skill-exchange-457f3.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCr3PTUzHBFXhDpQ8S2wN7XXW_-QIHowTg',
    appId: '1:252443331104:web:c059769e21f08b6335ca45',
    messagingSenderId: '252443331104',
    projectId: 'skill-exchange-457f3',
    authDomain: 'skill-exchange-457f3.firebaseapp.com',
    storageBucket: 'skill-exchange-457f3.firebasestorage.app',
    measurementId: 'G-XVKK3C9XGK',
  );
}
